src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $code_interface;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $telephone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="user", orphanRemoval=true)
     */
    private $commande;

    public function __construct()
    {
        $this->commande = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword()
    {
        // not needed for apps that do not check user passwords
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed for apps that do not check user passwords
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCodeInterface(): ?int
    {
        return $this->code_interface;
    }

    public function setCodeInterface(int $code_interface): self
    {
        $this->code_interface = $code_interface;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(?int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommande(): Collection
    {
        return $this->commande;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commande->contains($commande)) {
            $this->commande[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commande->contains($commande)) {
            $this->commande->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return (string) $this->getCodeInterface();
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Service\AppService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Security\LoginFormAuthenticator;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\User;
use App\Form\RegistrationType;


/**
 * Class SecurityController
 * @package App\Controller
 * @Route("/", name="app_")
 */
class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="login", methods={"GET","POST"})
     * @param AuthenticationUtils $authenticationUtils
     * @param AppService $appService
     * @return Response
     */
    public function login(AuthenticationUtils $authenticationUtils,AppService $appService ): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error,
        'titre_page'=> $appService->getTitre("login Page"),
        ]);
    }

    /**
     * @Route("/enregistrement", name="enregistrement", methods={"GET", "POST"})
     * @param Request $request
     * @param AppService $service
     * @param GuardAuthenticatorHandler $guardHandler
     * @param LoginFormAuthenticator $formAuthenticator
     * @return Response
     */
    public function register(Request $request,AppService $service, GuardAuthenticatorHandler $guardHandler, LoginFormAuthenticator $formAuthenticator)
    {
        // new instance de la Class User
        $user = new User();

        //On crée le form avec la class RegistrationType
        $form = $this->createForm(RegistrationType::class, $user);
        $form->handleRequest($request);

        //check si le form est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {

            //on persiste en db
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            //permettra de logger directemet le client crée sans avoir à passer par un login
            return $guardHandler->authenticateUserAndHandleSuccess(
                $user,
                $request,
                $formAuthenticator,
                'main'
            );
        }
        
        $codeclient=1234;
        return $this->render('security/enregistrement.html.twig', [
    
            'titre_page' => $service->getTitre("Enregistrement"),
            'form' => $form->createView(),
            'code'=> $codeclient,
        ]);

    }


    /**
     * @Route("/logout", name="logout")
     */
    public function logout()
    {
        return new \Exception("sera intercepté avant d´arriver ici");
    }
}

templates/security/_enregistrement.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enregistrement{% endblock %}

{% block body %}
<div class="d-flex justify-content-center container p-3 my-3">
    <div class="form">
    {{ form_start(form) }}
    {{ form_row(form.email,{ 'attr': {'class':'form-control mb-2 mr-sm-2'} }) }}<br>
   
    {{ form_row(form.codeInterface,{ 'attr': {'class':'form-control mb-2 mr-sm-2'} }) }}<br>
       <h2> le code a saisir  est le suivant: {{ code }}!!! </h2> 
       
        <button class="primary btn btn-success">Enregistrement</button> 
       
    </div>

    {{ form_end(form) }}

</div>

{% endblock %}

templates/security/_login.html.twig
<div class="formulaire">
<div class="container p-3 my-3 ">
    <h3 >Rentrez votre email et votre code</h3>
    <form method="post">

        {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" value="{{ last_username }}" id="email" placeholder="Rentrez votre email" name="email" required>
        </div>
        <div class="form-group">
            <label for="pwd">Code interface:</label>
            <input type="password" class="form-control" id="codeInterface" placeholder="Rentrez votre code" name="code_interface" required>
        </div>

        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}">
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="remember"> Remember me
            </label>
        </div>

          <button class="btn btn-success" type="submit">
                Valider</button>  
    </form>
</div>
</div>

templates/security/enregistrement.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}
    <!-- LE COMPOSANT NAVBAR -->

    {{ include('navbar.html.twig') }}

    <!-- FIN DU COMPOSANT NAVBAR -->

    <!-- LE COMPOSANT TITRE -->

    {{ include('titre.html.twig') }}

    <!-- FIN DU COMPOSANT TITRE -->

    <!-- LE COMPOSANT LOGIN -->

    {{ include('security/_enregistrement.html.twig') }}

    <!-- FIN COMPOSANT LOGIN -->
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <!-- LE COMPOSANT NAVBAR -->

    {{ include('navbar.html.twig') }}

    <!-- FIN DU COMPOSANT NAVBAR -->
    {% block title %}

        {{ include('titre.html.twig') }}

    {% endblock %}

    <!-- LE COMPOSANT LOGIN -->

    {{ include('security/_login.html.twig') }}

    <!-- FIN COMPOSANT LOGIN -->
{% endblock %}