src/Entity/Composer.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ComposerRepository")
 */
class Composer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantite;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produit", inversedBy="composer")
     * @ORM\JoinColumn(nullable=false)
     */
    private $produit;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Commande", inversedBy="composer")
     * @ORM\JoinColumn(nullable=false)
     */
    private $commande;

    /**
     * Composer constructor
     *
     * @param $quantite
     * @param $produit
     */
    public function __construct($quantite,$produit)
    {
        $this->quantite = $quantite;
        $this->produit = $produit;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(?int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->commande;
    }

    public function setCommande(?Commande $commande): self
    {
        $this->commande = $commande;

        return $this;
    }
    //récupère le montant total du panier
    public function getSousTotal()
    {
        return $this->quantite * $this->getProduit()->getPrixProduit();
    }
    //Converti le type int en string
    public function __toString()
    {
        return $this->getProduit()->getNomProduit();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %} Welcome to Fresh&Eat!{% endblock %}</title>

        {% block stylesheets %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
            <link rel="stylesheet" href="{{ asset('css/style.css') }}"/>
            <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet"/>
            <link href="/your-path-to-fontawesome/css/brands.css" rel="stylesheet"/>
            <link href="/your-path-to-fontawesome/css/solid.css" rel="stylesheet"/>

        {% endblock %}
    </head>
    <body>
        {% block body %}
            {{ include('navbar.html.twig') }}
            {{ include('titre.html.twig') }}

        {% endblock %}
            <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>{% endblock %}
    </body>
</html>

templates/navbar.html.twig
{% extends 'base.html.twig' %}

{% block body %}
 <nav class="navbar navbar-expand-xl bg-dark navbar-dark container-fluid ">
<!-- Brand/logo -->
     <nav class="navbar-nav">
     <a class="navbar-brand" href="#">
     <img src="/images/fhesE.png" alt="Logo" style="width:75px; hight:75px">
     </a>
     </nav>

<!-- Links -->
    <div class="nav-item col-sm-2 justify-content-start">
            <i class="fas fa-house-damage Home " ></i>
        <a class="nav-link" href="{{ path('resto_accueil')}}">Home</a>
    </div>


    {% if is_granted('ROLE_ADMIN') %}
        <div class="nav-item col-sm-2 justify-content-center">
                <i class="fas fa-utensils ListeP"></i>
            <a class="nav-link" href="{{ path('produit_liste') }}">Liste</a>
        </div>


        <div class="nav-item col-sm-2 justify-content-center">
            <i class="fas fa-user-friends Users"></i>  
           <a class="nav-link" href="#"> Serveur</a> 
            </div>
  
    
        <div class="nav-item col-sm-2 justify-content-center">
          <i class="fas fa-user-tie cuisine"></i>
          <a class="nav-link" href="#">Cuistot</a>
          </div>
  
         <div class="nav-item col-sm-2 justify-content-center">
           <i class="fas fa-user-tie caisse"></i> 
           <a class="nav-link" href="#">Caissier</a>
         </div>  
         
        
          <div class="nav-item col-sm-2 justify-content-center">
        <i class="fas fa-sign-out-alt logout"></i>
        <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
        </div>
   
     
    {% elseif is_granted('ROLE_CUISTOT') %}

        <div class="nav-item col-sm-2 justify-content-end ">
             <i class="fas fa-sign-out-alt logout"></i>
            <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
        </div>
        {% elseif is_granted('ROLE_SERVEUR') %}
     
        <div class="nav-item col-sm-5 justify-content-end">
                 <i class="fas fa-sign-out-alt logout"></i>
                  <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
        </div>

           {% elseif is_granted('ROLE_CAISSIER') %}

        <div class="nav-item col-sm-3 justify-content-end">
             <i class="fas fa-sign-out-alt logout"></i>
            <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
        </div>
    
    {% elseif is_granted('ROLE_USER') %}

        <div class="nav-item col-sm-3 justify-content-end" >
                <i class="fas fa-sign-out-alt logout"></i>
            <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
        </div>

        <div class="nav-item dropdown col-sm-9">
                <div class="Panier">
                    <i class="fas fa-shopping-cart"></i>
                    </div>
                <a  class="nav-link dropdown-toggle" data-toggle="dropdown"  href="#" style="margin-right: 7rem">Panier</a>
            <div class="dropdown-menu Cadis">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Produit</th>
                            <th>Quantité</th>
                            <th>Sous total</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for lc in lignesCmds %}
                            <tr>
                                <td>{{ lc.ligne_cmd }}</td>
                                <td class="align-center">{{ lc.ligne_cmd.quantite }}</td>
                                <td class="align-center">
                                    <strong>{{ lc.ligne_cmd.sousTotal }}<i class='fas fa-euro-sign'></i></strong>
                                </td>
                                <td>
                                    <button>
                                        <a href="{{path('panier_supprimer',{id: lc.ligne_cmd.produit.id })}}" class="panierActionSupprimer">
                                            <i class="fas fa-trash-alt"></i> </a>
                                    </button>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="4">Le panier est vide</td>
                            </tr>
                        {% endfor %}
                        {% if total > 0 %}
                            <tr class="total">
                                <td colspan="2" class="text-right">
                                    <strong>TOTAL</strong>
                                </td>
                                <td class="text-right primary">
                                    <strong>{{ total }}€</strong>
                                </td>
                            </tr>
                        {% endif %}
                        </tbody>
 </table>
<button class="btn btn-success">
    <a href="{{path('panier_valider')}}">Valider</a>
</button>
  </div>
         
       
    {% endif %} 
          </div>
          </nav>
 </nav>
{% endblock %}

templates/titre.html.twig
<!--LE COMPOSANT TITRE -->
<div class="titrePage"> 
        <h1 class="titrePage container d-flex justify-content-center text-white">{{ titre_page }}</h1>
</div>
<!--FIN DU COMPOSANT TITRE -->